apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-chaos
spec:
  action: pod-failure
  mode: fixed
  value: "2"
  duration: '60s'
  selector:
    namespaces:
      - ${ns}
    labelSelectors:
      "app.kubernetes.io/name": "broker"