name: PUSH-CI

on:
  push:
    branches: [master, develop]

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
  DOCKER_REPO: registry.cn-guangzhou.aliyuncs.com/cc-aliyun/rocketmq-ci

jobs:
  deploy-benchmark:
    if: ${{ success() }}
    name: Deploy RocketMQ For Benchmarking
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        version: ["fix-benchmark-e2e-dependency-5f64a9ae-157d-40c0-9c6f-638fc2ee6fb7-ubuntu"]
    steps:
      - uses: chi3316/rocketmq-test-tool@44a9a6239a5f3f194fe918accd5a41662d9fc5d1
        name: Deploy rocketmq
        with:
          action: "deploy"
          ask-config: "${{ secrets.ASK_CONFIG_VIRGINA }}"
          test-version: "${{ matrix.version }}"
          chart-git: "https://github.com/apache/rocketmq-docker.git"
          chart-branch: "master"
          chart-path: "./rocketmq-k8s-helm"
          job-id: "001-${{ strategy.job-index }}"
          helm-values: |
            nameserver:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            broker:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            proxy:
              image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}
            controller:
               image:
                repository: ${{env.DOCKER_REPO}}
                tag: ${{ matrix.version }}

  benchmark-test:
    if: ${{ success() }}
    # ubuntu-22.04
    runs-on: ubuntu-latest
    name: Performance benchmark test
    needs: [ deploy-benchmark ]
    timeout-minutes: 60
    steps:
      - uses: chi3316/rocketmq-test-tool/benchmark-runner@39cba2235ce88a56c0cf4031648745f23e356e45
        name: Performance benchmark
        with:
          action: "performance-benchmark"
          ask-config: "${{ secrets.ASK_CONFIG_VIRGINA }}"
          job-id: "001-${{ strategy.job-index }}"
          # The time to run the test, 15 minutes
          test-time: "900"
          # Some thresholds set in advance
          min-send-tps-threshold: "12000"
          max-rt-ms-threshold: "500"
          avg-rt-ms-threshold: "10"
          max-2c-rt-ms-threshold: "100"
          avg-2c-rt-ms-threshold: "10"
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-report
          path: benchmark/

  clean-benchmark:
    if: always()
    name: Clean Benchmarking
    needs: [ benchmark-test ]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        version: ["fix-benchmark-pipeline-os-version-4df03f1e-5b81-4290-bdb9-377d5ce03424-ubuntu"]
    steps:
      - uses: chi3316/rocketmq-test-tool@44a9a6239a5f3f194fe918accd5a41662d9fc5d1
        name: clean
        with:
          action: "clean"
          ask-config: "${{ secrets.ASK_CONFIG_VIRGINA }}"
          test-version: "${{ matrix.version }}"
          job-id: "001-${{ strategy.job-index }}"